### PR TITLE
Don't use globals for platforms and components registration

### LINKED ISSUE #597: Don't use globals for handling components and platforms registration
The overhead of adding them is very little if we use the implementation, which do not use globals.

Similar to #596.

### LINKED ISSUE #992: Lokoctl uses global variable which gives wrong results if used via APIs
Consider following test code:

```go
func TestConversion(t *testing.T) {
	testCases := []struct {
		Name        string
		InputConfig string
		Contains    string
	}{
		{
			Name:     "use external_url param",
			Contains: "https://prometheus.externalurl.net",
			InputConfig: `
component "prometheus-operator" {
  prometheus {
    external_url = "https://prometheus.externalurl.net"
  }
}
`,
		},
		{
			Name:     "no external_url param",
			Contains: "https://prometheus.mydomain.net",
			InputConfig: `
component "prometheus-operator" {
  prometheus {
    ingress {
      host                       = "prometheus.mydomain.net"
      class                      = "contour"
      certmanager_cluster_issuer = "letsencrypt-production"
    }
  }
}
`,
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.Name, func(t *testing.T) {
			m := renderManifests(t, tc.InputConfig)
			gotConfig := m["prometheus-operator/templates/prometheus/prometheus.yaml"]

			scanner := bufio.NewScanner(strings.NewReader(gotConfig))
			for scanner.Scan() {
				line := scanner.Text()
				if !strings.Contains(line, "externalUrl") {
					continue
				}

				t.Logf("\nwanted =   externalUrl: %q.\ngot    = %s", tc.Contains, line)
			}
		})
	}
}
```

Whose output looks like this:

```console
$ go test -v github.com/kinvolk/lokomotive/pkg/components/prometheus-operator -run TestConversion
=== RUN   TestConversion
=== RUN   TestConversion/use_external_url_param
    component_conversion_test.go:92: 
        wanted =   externalUrl: "https://prometheus.externalurl.net".
        got    =   externalUrl: "https://prometheus.externalurl.net"
=== RUN   TestConversion/no_external_url_param
    component_conversion_test.go:92: 
        wanted =   externalUrl: "https://prometheus.mydomain.net".
        got    =   externalUrl: "https://prometheus.externalurl.net"
--- PASS: TestConversion (1.86s)
    --- PASS: TestConversion/use_external_url_param (0.89s)
    --- PASS: TestConversion/no_external_url_param (0.97s)
PASS
ok      github.com/kinvolk/lokomotive/pkg/components/prometheus-operator        1.906s
```

Notice that in second test case we should see `https://prometheus.mydomain.net` but the old result persists for some reason. My first guess is that this is due to use of globals.

I think `component.LoadConfig` and `component.RenderManifests` don't do the right thing. Or we should flush out old values when `components.Get` is called.

```go
func renderManifests(t *testing.T, configHCL string) map[string]string {
	name := "prometheus-operator"

	component, err := components.Get(name)
	if err != nil {
		t.Fatalf("Getting component %q: %v", name, err)
	}

	body, diagnostics := util.GetComponentBody(configHCL, name)
	if diagnostics != nil {
		t.Fatalf("Getting component body: %v", diagnostics)
	}

	diagnostics = component.LoadConfig(body, &hcl.EvalContext{})
	if diagnostics.HasErrors() {
		t.Fatalf("Valid config should not return an error, got: %s", diagnostics)
	}

	ret, err := component.RenderManifests()
	if err != nil {
		t.Fatalf("Rendering manifests with valid config should succeed, got: %s", err)
	}

	return ret
}
```

### PR DESCRIPTION
**Pull request by invidian**
~**This pull request includes commits from #1098, please do not review commits from #1098 in this pull request**~

Closes #992
Closes #597

See commit messages for details.

### CODE REVIEW

File: pkg/platform/aws/aws.go [hunk 1]
```diff
@@ -88,6 +88,11 @@ type config struct {
...
 }
 
+const (
+	// Name represents AWS platform name as it should be referenced in function calls and configuration.
+	Name = "aws"
+)
+
 // init registers aws as a platform
 func init() {
 	platform.Register("aws", NewConfig())
```
Comment (knrt10) [inline pkg/platform/aws/aws.go]: Can you please use the constant here also? Also, why not merge this commit and aks one?

```suggestion
platform.Register(Name, NewConfig())
```

File: pkg/platform/baremetal/baremetal.go [hunk 2]
```diff
@@ -60,6 +60,11 @@ type config struct {
 	KubeAPIServerExtraFlags  []string
 }
 
+const (
+	// Name represents bare-metal platform name as it should be referenced in function calls and configuration.
```
Comment (knrt10) [inline pkg/platform/baremetal/baremetal.go:64]: We should be consistent like other platforms.

```suggestion
      // Name represents Bare-metal platform name as it should be referenced in function calls and configuration.
```

File: pkg/platform/baremetal/baremetal.go [hunk 3]
```diff
@@ -60,6 +60,11 @@ type config struct {
...
+	Name = "bare-metal"
+)
+
 // init registers bare-metal as a platform
 func init() {
 	platform.Register("bare-metal", NewConfig())
```
Comment (knrt10) [inline pkg/platform/baremetal/baremetal.go]: Same

File: pkg/platform/packet/packet.go [hunk 4]
```diff
@@ -102,6 +102,11 @@ type config struct {
...
 }
 
+const (
+	// Name represents Packet platform name as it should be referenced in function calls and configuration.
+	Name = "packet"
+)
+
 // init registers packet as a platform
 func init() {
 	platform.Register("packet", NewConfig())
```
Comment (knrt10) [inline pkg/platform/packet/packet.go]: Same

File: pkg/platform/aws/aws.go (hunk 1 above)
Comment (knrt10) [reply pkg/platform/aws/aws.go]: Now that I think of it, as you removed init function in the next commit. I would say it is un-necessary. But I would suggest merging this commit with AKS one.

File: pkg/components/cluster-autoscaler/component.go [hunk 5]
```diff
@@ -118,7 +118,10 @@ type packetConfiguration struct {
 	AuthToken     string
 }
 
-func newComponent() *component {
+// NewConfig returns new Cluster Autoscaler component configuration with default values set.
```
Comment (knrt10) [inline pkg/components/cluster-autoscaler/component.go:117]: We should be consistent with the component name as used in the previous commit.

```suggestion
// NewConfig returns new cluster-autoscaler component configuration with default values set.
```

File: pkg/components/external-dns/component.go [hunk 6]
```diff
@@ -88,7 +88,10 @@ type component struct {
 	OwnerID        string    `hcl:"owner_id"`
 }
 
-func newComponent() *component {
+// NewConfig returns new ExternalDNS component configuration with default values set.
```
Comment (knrt10) [inline pkg/components/external-dns/component.go:87]:
```suggestion
// NewConfig returns new external-dns component configuration with default values set.
```

File: pkg/components/linkerd/component.go [hunk 7]
```diff
@@ -56,7 +56,10 @@ type cert struct {
 	Expiry string
 }
 
-func newComponent() *component {
+// NewConfig returns new Istio component configuration with default values set.
```
Comment (knrt10) [inline pkg/components/linkerd/component.go:54]: This is Linkerd 🙈 

```suggestion
// NewConfig returns new Linkerd component configuration with default values set.
```

**Review by knrt10 — CHANGES_REQUESTED** [review]
Awesome work 🥳 . Some suggestions.

File: pkg/components/external-dns/component.go (hunk 6 above)
Comment (invidian) [reply pkg/components/external-dns/component.go:87]: `ExternalDNS` is the official form of the project name: https://github.com/kubernetes-sigs/external-dns#externaldns.

Comment (knrt10) [reply pkg/components/external-dns/component.go:87]: Cool, then it needs to be fixed for the previous commit then

File: pkg/components/linkerd/component.go (hunk 7 above)
Comment (invidian) [reply pkg/components/linkerd/component.go:54]: Nice catch, fixed, thanks!

File: pkg/components/cluster-autoscaler/component.go (hunk 5 above)
Comment (invidian) [reply pkg/components/cluster-autoscaler/component.go:117]: Ditto official name: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#cluster-autoscaler

File: pkg/platform/aws/aws.go (hunk 1 above)
Comment (invidian) [reply pkg/platform/aws/aws.go]: Yes, I should've done this. Will fix regardless.

File: pkg/platform/baremetal/baremetal.go (hunk 2 above)
Comment (invidian) [reply pkg/platform/baremetal/baremetal.go:64]: True, but it should be `Bare Metal`, as in quickstart guide.

File: pkg/components/external-dns/component.go (hunk 6 above)
Comment (invidian) [reply pkg/components/external-dns/component.go:87]: Right, fixing.

File: pkg/components/cluster-autoscaler/component.go (hunk 5 above)
Comment (invidian) [reply pkg/components/cluster-autoscaler/component.go:117]: Fixed.

File: cli/cmd/cluster/cluster.go [hunk 8]
```diff
@@ -30,12 +30,6 @@ import (
 	"github.com/kinvolk/lokomotive/pkg/platform"
```
Comment (surajssd) [inline cli/cmd/cluster/cluster.go:29]: > All platform packages are now imported by utils.go file, so anonymous imports are no longer needed.

I am not sure if this commit message is valid. The anonymous imports are not needed anymore because we don't rely on the init function call registration method. So importing in `utils.go` or not does not matter.

File: test/components/install_test.go [hunk 9]
```diff
@@ -20,35 +20,13 @@ package components
 import (
 	"testing"
 
-	"github.com/hashicorp/hcl/v2"
-
-	"github.com/kinvolk/lokomotive/pkg/components"
-	_ "github.com/kinvolk/lokomotive/pkg/components/flatcar-linux-update-operator"
+	flatcarlinuxupdateoperator "github.com/kinvolk/lokomotive/pkg/components/flatcar-linux-update-operator"
```
Comment (surajssd) [inline test/components/install_test.go:23]: fluo in short?

File: pkg/components/dex/component_test.go [hunk 10]
```diff
@@ -17,7 +17,7 @@ package dex_test
 import (
```
Comment (surajssd) [inline pkg/components/dex/component_test.go:17]: Typo in commit message: `realy`.

**Review by surajssd — CHANGES_REQUESTED** [review]
We also need to parallelize the tests.

File: pkg/platform/aws/aws.go [hunk 11]
```diff
@@ -88,9 +88,14 @@ type config struct {
 	KubeAPIServerExtraFlags  []string
 }
 
+const (
```
[the remark this answers is not in the document]
Comment (invidian) [reply pkg/platform/aws/aws.go:91]: Commit as doing different things. One is exposing things, other is adding new exported const. Both commit still do one thing each, just in multiple contexts. I think I prefer to keep them separate.

File: cli/cmd/cluster/cluster.go (hunk 8 above)
Comment (invidian) [reply cli/cmd/cluster/cluster.go:29]: Good point. Fixed.

**Comment by invidian** [comment]
>We also need to parallelize the tests.

Which ones? I'm almost sure this is out of scope of this (already large) PR.

If you talk about the unit tests using configuration, I think we should fix them either on the way OR in a separate PR as part of other issue.

@surajssd addressed remaining review comments, please have a look again.

**Comment by surajssd** [comment]
> If you talk about the unit tests using configuration, I think we should fix them either on the way OR in a separate PR as part of other issue.

The promise of this change is that tests could be parallelised which weren't because we were extracting the same object from global store. So how do we confirm that promise is fullfilled with this change?

**Comment by invidian** [comment]
>The promise of this change is that tests could be parallelised which weren't because we were extracting the same object from global store. So how do we confirm that promise is fullfilled with this change?

There is no global registry anymore and it's up to the package itself to ensure immutability, as `NewConfig()` function returns a pointer to configuration. Each package must ensure this pointer is unique, not taken from global, which is the case. It will be fine :)

**Comment by invidian** [comment]
I need to rebase.

**Comment by invidian** [comment]
Rebased to also adapt Tinkerbell platform for introduced changes.

File: cli/cmd/cluster/component.go [hunk 12]
```diff
@@ -15,33 +15,74 @@
...
-	_ "github.com/kinvolk/lokomotive/pkg/components/openebs-storage-class"
-	_ "github.com/kinvolk/lokomotive/pkg/components/prometheus-operator"
-	_ "github.com/kinvolk/lokomotive/pkg/components/rook"
-	_ "github.com/kinvolk/lokomotive/pkg/components/rook-ceph"
-	_ "github.com/kinvolk/lokomotive/pkg/components/velero"
-	_ "github.com/kinvolk/lokomotive/pkg/components/web-ui"
+	"fmt"
 
 	"github.com/kinvolk/lokomotive/pkg/components"
+	awsebscsidriver "github.com/kinvolk/lokomotive/pkg/components/aws-ebs-csi-driver"
```
Comment (iaguis) [inline cli/cmd/cluster/component.go:21]: ew, this looks ugly but I guess that's the way it is :D

**Review by iaguis — APPROVED** [review]
LGTM. Thanks for getting rid of all those terrible `init()` functions!

File: cli/cmd/cluster/component.go (hunk 12 above)
Comment (invidian) [reply cli/cmd/cluster/component.go:21]: Looks like cat running over the keyboard, indeed :smile:
