### PR TITLE
pkg/components/cluster-autoscaler: fix checking device uniqueness

### LINKED ISSUE #766: Fix device uniqueness check from cluster-autoscaler component
Considering following real-life scenario:
- User X creates cluster A named "foo".
- User X creates cluster B also named "foo" (Packet allows that).
- User Y creates cluster C named "bar".

All clusters are created in the same facility.

Now, if user Y tries to install `cluster-autoscaler` component, it will fail, as facility have 2 devices with the same name, despite **they don't even belong to user Y clusters**.

This is because we check device uniqueness before checking the cluster name on the devices, here: https://github.com/kinvolk/lokomotive/blob/master/pkg/components/cluster-autoscaler/component.go#L154-L165. This seems like incorrect behavior. Unfortunately, there is no tests to confirm/deny that.

### PR DESCRIPTION
**Pull request by invidian**
Considering following real-life scenario:

- User X creates cluster A named "foo".
- User X creates cluster B also named "foo" (Packet allows that).
- User Y creates cluster C named "bar".

All clusters are created in the same facility.

Now, if user Y tries to install cluster-autoscaler component, it will
fail, as facility have 2 devices with the same name, despite they don't
even belong to user Y clusters.

This is because we check device uniqueness before checking the cluster
name on the devices, which seems incorrect.

This commit breaks down 'getWorkerUserdata()' function into few smaller
functions to make it more readable and to allow implementing simple
tests for the desired behavior.

Also, previously we were returning userData of last node found and now
we return userData of first node, to simplify the code. There is also a
test included for it now.

This commit should also simplify fixing #767.

Closes #766.

The tests could be smarter and we are testing unexported functions, which is generally not recommended, but it should be OK for now.

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

### CODE REVIEW

File: pkg/components/cluster-autoscaler/component.go [hunk 1]
```diff
@@ -139,37 +139,85 @@ func newComponent() *component {
...
+			continue
 		}
 
-		// if device hostname contains the cluster name and "worker", we want
-		// its user data
-		if strings.Contains(d.Hostname, clusterName) &&
-			strings.Contains(d.Hostname, "worker") {
-			userData = base64.StdEncoding.EncodeToString([]byte(d.UserData))
+		// Skip controller nodes.
+		if !strings.Contains(d.Hostname, "worker") {
```
Comment (surajssd) [inline pkg/components/cluster-autoscaler/component.go:159]: Just curious why the check is `not wokers` vs `controllers`?

File: pkg/components/cluster-autoscaler/component_internal_test.go [hunk 2]
```diff
@@ -0,0 +1,319 @@
...
+	if userdata, _ := getWorkerUserdata("", "", []packngo.Device{}); userdata != "" {
+		t.Fatalf("if error is returned, no userdata should be returned either")
+	}
+}
+
+func TestGetWorkerUserdataNoWorkers(t *testing.T) {
+	if _, err := getWorkerUserdata("", "", []packngo.Device{}); err == nil {
+		t.Fatalf("if there is no devices to get user data from, error should be returned")
+	}
+}
```
Comment (surajssd) [inline pkg/components/cluster-autoscaler/component_internal_test.go:170]: Aren't these two same tests? Since the test input is same I think both can be coupled into one test.

File: pkg/components/cluster-autoscaler/component.go (hunk 1 above)
Comment (invidian) [reply pkg/components/cluster-autoscaler/component.go:159]: Well, there could possibly be other type of nodes in the future :smile: also this was in the original code. Maybe I change the commit to `Skip non-worker nodes.` ?

File: pkg/components/cluster-autoscaler/component_internal_test.go (hunk 2 above)
Comment (invidian) [reply pkg/components/cluster-autoscaler/component_internal_test.go:170]: Yes, it should be fine to merge them.

File: pkg/components/cluster-autoscaler/component.go (hunk 1 above)
Comment (invidian) [reply pkg/components/cluster-autoscaler/component.go:159]: Changed the comment.

File: pkg/components/cluster-autoscaler/component_internal_test.go (hunk 2 above)
Comment (invidian) [reply pkg/components/cluster-autoscaler/component_internal_test.go]: Merged.

**Comment by knrt10** [comment]
I was about to make a small PR for code spell ignoring `gif` file. Thanks for adding this in this commit

**Comment by surajssd** [comment]
@invidian One last thing which I forgot before, please mark these tests to run in parallel?

**Comment by invidian** [comment]
>@invidian One last thing which I forgot before, please mark these tests to run in parallel?

Is it really necessery?

```sh
0 ✓ (444ms) 12:24:12 invidian@dellxps15mateusz ~/repos/kinvolk/lokomotive (invidian/cluster-autoscaler-fix-duplicated-nodes)$ go test -v -count=1 ./pkg/components/cluster-autoscaler/
=== RUN   TestGetClusterWorkersFilterByFacility
--- PASS: TestGetClusterWorkersFilterByFacility (0.00s)
=== RUN   TestGetClusterWorkersFilterByCluster
--- PASS: TestGetClusterWorkersFilterByCluster (0.00s)
=== RUN   TestGetClusterWorkersFilterNonWorkers
--- PASS: TestGetClusterWorkersFilterNonWorkers (0.00s)
=== RUN   TestFindDuplicatedDevicesNonUniqueHostname
--- PASS: TestFindDuplicatedDevicesNonUniqueHostname (0.00s)
=== RUN   TestFindDuplicatedDevicesUniqueHostname
--- PASS: TestFindDuplicatedDevicesUniqueHostname (0.00s)
=== RUN   TestDeviceHostnames
--- PASS: TestDeviceHostnames (0.00s)
=== RUN   TestGetWorkerUserdataNoUserdataOnError
--- PASS: TestGetWorkerUserdataNoUserdataOnError (0.00s)
=== RUN   TestGetWorkerUserdataDuplicatedWorkers
--- PASS: TestGetWorkerUserdataDuplicatedWorkers (0.00s)
=== RUN   TestGetWorkerUserdataEmptyUserdata
--- PASS: TestGetWorkerUserdataEmptyUserdata (0.00s)
=== RUN   TestGetWorkerUserdataFirstDevice
--- PASS: TestGetWorkerUserdataFirstDevice (0.00s)
=== RUN   TestGetWorkerUserdataReturnBase64
--- PASS: TestGetWorkerUserdataReturnBase64 (0.00s)
=== RUN   TestGetWorkerUserdataDuplicatedWorkersDifferentClusters
--- PASS: TestGetWorkerUserdataDuplicatedWorkersDifferentClusters (0.00s)
=== RUN   TestGetWorkerUserdataDuplicatedWorkersIncludeHostnames
--- PASS: TestGetWorkerUserdataDuplicatedWorkersIncludeHostnames (0.00s)
=== RUN   TestEmptyConfig
--- PASS: TestEmptyConfig (0.00s)
=== RUN   TestEmptyBody
--- PASS: TestEmptyBody (0.00s)
=== RUN   TestRender
--- PASS: TestRender (0.00s)
PASS
ok      github.com/kinvolk/lokomotive/pkg/components/cluster-autoscaler 0.029s
0 ✓ (2.228s) 12:24:21 invidian@dellxps15mateusz ~/repos/kinvolk/lokomotive (invidian/cluster-autoscaler-fix-duplicated-nodes)$
```

**Comment by surajssd** [comment]
> Is it really necessery?

What's wrong with parallelizing the unit tests?

**Comment by invidian** [comment]
>What's wrong with parallelizing the unit tests?

It's a lot of boilerplate to add with almost no gain. The test execution takes `0.029s`. How lower you want to get it? I think by the rule of thumb, if test takes more than a second, then it make sense to parallelize it, so rest of the test suite does not wait for this one.

**Comment by surajssd** [comment]
> It's a lot of boilerplate to add with almost no gain. The test execution takes 0.029s. How lower you want to get it? I think by the rule of thumb, if test takes more than a second, then it make sense to parallelize it, so rest of the test suite does not wait for this one.

I think it sets a precedent for other tests as well. As in when someone else looks at code and tries to write similar tests it becomes a norm to make it parallel.

What is it that we are losing by making it parallel I don't understand though :confused:?

**Comment by invidian** [comment]
>I think it sets a precedent for other tests as well.

Still, the delay of `0.029s`.

>What is it that we are losing by making it parallel I don't understand though confused?

As I said, we add boilerplate code, which is not really needed, as there is almost no gain from it.
