### PR TITLE
Fix controlplane running as DaemonSet on single node clusters

### LINKED ISSUE #90: Ensure that controlplane pods are spread equally across controller nodes
`kube-controller-manager` and `kube-scheduler` use Deployment object with `preferredDuringSchedulingIgnoredDuringExecution`, which means that during scheduling, pods will be equally spread across nodes. However, if there is only one controller node available during bootstrapping (it does happen, as nodes join without particular order), then all pods are getting scheduled on this single node. If this node fails, then the entire controlplane goes down, which gives user a false sense of redundancy of the controlplane.

We should ensure, that those pods are always scheduled equally across nodes to maximize the redundancy.

One way of achieving that would be to use `requiredDuringSchedulingIgnoredDuringExecution` instead of `preferredDuringSchedulingIgnoredDuringExecution`, however that has negative effect when having just a single controlplane node, that more than one pod cannot be scheduled on a single node, and that is recommended for doing upgrades, so we would have to do that conditionally.

The alternative would be to use [descheduler](https://github.com/kubernetes-sigs/descheduler), which would periodically ensure, that pods are spread.

Currently for `kube-apiserver` we use DaemonSet, which makes sure that their pods are equally spread across controller nodes, but might be changed to `Deployment` as well, if #32 gets merged.

### LINKED ISSUE #1097: kube-controller-manager doesn't respawn with 1 controller
In https://github.com/kinvolk/lokomotive/pull/1030/commits/3c1fb4a625791411f9b7cbf499bc193f7491d41a (#1030) we've changed kube-controller-manager from a deployment to a daemonset when the number of controller nodes is greater than one. However, looks like we create a daemonset also when running with one controller. The reason for that is the following:

https://github.com/kinvolk/lokomotive/blob/c73006679aa69de0a67adbb4eafd22cbfade1444/assets/charts/control-plane/kubernetes/templates/kube-controller-manager-ds.yaml#L1

https://github.com/kinvolk/lokomotive/blob/c73006679aa69de0a67adbb4eafd22cbfade1444/assets/terraform-modules/bootkube/assets.tf#L72

As can be seen, when deploying a single controller node `max(2, length(var.etcd_servers))` evaluates to `2`, which makes the conditional in the chart be always true.

To fix this we could change the conditional to be `{{- if gt (int .Values.controllerManager.controlPlaneReplicas) 2 }}`.

>NOTE: If we change the Helm conditional, we should probably do it for other control plane elements, too. Even if the impact isn't the same, other elements are likely also affected by this bug.

**However**, I'm not sure we ever want to use a daemonset for kube-controller-manager. A deployment is better suited for this element because our goal is to have _a consistent number of replicas_ in the cluster, not to have _a replica on each node_. Furthermore, I'm not sure there is a point in running **more** than two replicas when there are multiple controller nodes, unless we aim at surviving a dual failure (in which case there are likely many other things we would have to change). AFAICT a total of two kube-controller-manager pods should be the minimum and should suffice as the maximum as well.

Since kube-controller-manager is the element that's responsible for re-creating pods when a pod gets deleted, at least one kube-controller-manager pod must be operational at all times. Right now, when deploying a cluster with a single controller node, deleting the kube-controller-manager pod puts the cluster in an unrecoverable state because there is no kube-controller-manager to re-create the deleted kube-controller-manager pod.

I understand the concern about having multiple replicas land on a single node. Still, I think we should figure out other ways to solve that problem and in any case the situation is currently worse than before #1030 when running with a single controller node: Before the PR we would have a broken control plane when the controller node dies, however would recover from pod deletions. Now the cluster still breaks when the controller node dies, however we no longer recover from deleting the kube-controller-manager pod (and likely from evictions of that pod, too).

Related issues:

- https://github.com/kinvolk/lokomotive/issues/90

@surajssd - FYI.

### PR DESCRIPTION
**Pull request by invidian**
This commit fixes passed 'control_plane_replicas' value to Kubernetes
Helm chart which caused kube-scheduler and kube-controller-manager to
run as DaemonSet on single controlplane node clusters, which breaks the
ability to update it gracefully.

It also adds tests that controlplane is using right resource type on
different controlplane sizes and that both can be gracefully updated
without breaking cluster functionality.

Closes #1097
Closes #90

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

### CODE REVIEW

**Comment by invidian** [comment]
Had to fix testing logic a bit and extend wait times to make sure we test properly. it should work fine now.

**Comment by invidian** [comment]
Tests failed once on AWS, but then passed 3 times, so I think they are stable enough.

**Comment by johananl** [comment]
@invidian I can't review this right now due to load, sorry. Please assign someone else.

File: test/components/kubernetes/controlplane-single-node_test.go [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+)
+
+func Test_Controlplane_components_are_Deployments_on_single_controller_node_cluster(t *testing.T) {
+	client := testutil.CreateKubeClient(t)
+
+	for c := range components() {
+		c := c
+
+		t.Run(c, func(t *testing.T) {
+			t.Parallel()
```
Comment (surajssd) [inline test/components/kubernetes/controlplane-single-node_test.go:37]: We should stop running diruptivee2e type tests in parallel. This will only make it harder for us to debug which caused race for others.

File: test/components/util/util.go [hunk 2]
```diff
@@ -164,7 +164,9 @@ func WaitForDaemonSet(t *testing.T, client kubernetes.Interface, ns, name string
 				return false, nil
 			}
 
-			return false, fmt.Errorf("getting DaemonSet %q: %w", name, err)
+			t.Logf("getting DaemonSet %q: %v", name, err)
```
Comment (surajssd) [inline test/components/util/util.go:167]: Depending on the main-retry-loop to retry can elongate the time for test if there actually is error and not something transient. We might think about introducing shorter retry for such stuff. This does not have to be here, could reside outside as a helper func.

File: test/components/kubernetes/controlplane-single-node_test.go (hunk 1 above)
Comment (invidian) [reply test/components/kubernetes/controlplane-single-node_test.go:37]: This one is actually OK to run in parallel, it only verifies that all deployments converged. It's not disruptive, but should run as part of disruptive tests.

File: test/components/util/util.go (hunk 2 above)
Comment (invidian) [reply test/components/util/util.go:167]: Right. But on the other hand, it also gives more time to investigate when you see that it loops here.

File: test/components/kubernetes/controlplane-single-node_test.go (hunk 1 above)
Comment (surajssd) [reply test/components/kubernetes/controlplane-single-node_test.go:37]: Separate file is what I would go. Because diruptivee2e has potential to disrupt the tests :laughing:

Comment (invidian) [reply test/components/kubernetes/controlplane-single-node_test.go:37]: OK, done. Please have a look again.

File: test/components/kubernetes/controlplane-multi-node_disruptive_test.go [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+import (
+	"context"
+	"testing"
+	"time"
+
+	testutil "github.com/kinvolk/lokomotive/test/components/util"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+)
+
+func Test_Controlplane_components_DaemonSets_can_be_gracefully_updated(t *testing.T) {
```
Comment (iaguis) [inline test/components/kubernetes/controlplane-multi-node_disruptive_test.go:29]: Please revert to the current convention (https://github.com/kinvolk/lokomotive/pull/1181#pullrequestreview-537548039).

File: test/components/kubernetes/controlplane-multi-node_disruptive_test.go [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+	client := testutil.CreateKubeClient(t)
+	deployClient := client.AppsV1().DaemonSets(namespace)
```
Comment (iaguis) [inline test/components/kubernetes/controlplane-multi-node_disruptive_test.go:31]: Copypasta? This should be daemoset or ds.

**Review by iaguis — CHANGES_REQUESTED** [review]
Any idea how this impacts updates from v0.5.0?

File: test/components/kubernetes/controlplane-multi-node_disruptive_test.go (hunk 3 above)
Comment (invidian) [reply test/components/kubernetes/controlplane-multi-node_disruptive_test.go]: Reverted snake case but kept the naming convention. I hope that's all right.

File: test/components/kubernetes/controlplane-multi-node_disruptive_test.go (hunk 4 above)
Comment (invidian) [reply test/components/kubernetes/controlplane-multi-node_disruptive_test.go]: Yes, thanks, fixed.

**Review by iaguis — DISMISSED** [review]
lgtm

**Comment by invidian** [comment]
>lgtm

Thanks @iaguis :)

>Any idea how this impacts updates from v0.5.0?

I'll actually test that before merging.

**Comment by invidian** [comment]
>I'll actually test that before merging.

Tested, it magically works completely fine :smile:

**Review by surajssd — DISMISSED** [review]

File: test/components/util/util.go [hunk 5]
```diff
@@ -164,7 +164,9 @@ func WaitForDaemonSet(t *testing.T, client kubernetes.Interface, ns, name string
 				return false, nil
```
Comment (surajssd) [inline test/components/util/util.go:164]: Spell in commit `transient`

Comment (invidian) [reply test/components/util/util.go:164]: Thanks, fixed.

**Review by iaguis — APPROVED** [review]
lgtm
